version: "3"

services:
  fuseki:
    image: ubleipzig/fuseki:3.7.0
    container_name: fuseki
    restart: always
    environment:
        CATALINA_OPTS: -Xmx8G -Xss8M
        FUSEKI_CONF: /tmp/fuseki-conf
    ports:
      - "3030:3030"
      - "8443:8443"
    volumes:
      - triplestore-data-volume:/shared/fuseki-data/trellis_data
      - triplestore-backup-volume:/shared/fuseki-data/backups

volumes:
  triplestore-data-volume:
    driver_opts:
      type: none
      device: /mnt/fuseki-data
      o: bind
  triplestore-backup-volume:
    driver_opts:
      type: none
      device: /mnt/fuseki-backup
      o: bind