apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka
    spec:
      containers:
      - env:
        - name: HOSTNAME_COMMAND
          value: ifconfig|grep inet|head -1|sed 's/\:/ /'|awk '{print $3}'
        - name: KAFKA_ADVERTISED_PORT
          value: "9094"
        - name: KAFKA_ADVERTISED_PROTOCOL_NAME
          value: OUTSIDE
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "5000000"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_PROTOCOL_NAME
          value: INSIDE
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        image: trellisldp/kafka:1.0.0
        name: kafka
        ports:
        - containerPort: 9094
        - containerPort: 1099
        resources: {}
        volumeMounts:
        - mountPath: /kafka
          name: kafka-data-volume
      restartPolicy: Always
      volumes:
      - name: kafka-data-volume
        persistentVolumeClaim:
          claimName: kafka-data-volume
status: {}
