apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: trellis
  name: trellis
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8502"
    port: 8502
    targetPort: 8081
  selector:
    io.kompose.service: trellis
status:
  loadBalancer: {}
