---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trellis
  name: trellis-svc
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8502"
    port: 8502
    targetPort: 8081
  selector:
    app: trellis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: trellis
  name: trellis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trellis
    spec:
      containers:
      - image: trellisldp/trellis-app-dev:0.1.6
        name: trellis
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        ports:
        - containerPort: 8080
        - containerPort: 8081
        lifecycle:
          postStart:
            exec:
              command: ['sh', '-c', 'gcsfuse -o nonempty trellis-binaries /mnt/binaries']
          preStop:
            exec:
              command: ["fusermount", "-u", " /mnt/binaries"]
        volumeMounts:
        - mountPath: /var/lib/trellis
          name: datadir-trellis
      restartPolicy: Always
      volumes:
      - name: datadir-trellis
        persistentVolumeClaim:
          claimName: datadir-trellis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: datadir-trellis
  name: datadir-trellis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
