apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: trellis
  name: trellis
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: trellis
    spec:
      containers:
      - image: trellisldp/trellis-app-dev:0.1.2
        name: trellis
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/trellis
          name: trellis-data-volume
      restartPolicy: Always
      volumes:
      - name: trellis-data-volume
        persistentVolumeClaim:
          claimName: trellis-data-volume
status: {}
