---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trellis-processing
  name: trellis-processing
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: trellis-processing
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: trellis-processing
  name: trellis-processing
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trellis-processing
    spec:
      containers:
      - image: trellisldp/trellis-processing-k8s
        name: trellis-processing
        volumeMounts:
        - mountPath: /var/lib/trellis
          name: datadir-trellis
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ['sh', '-c', 'gcsfuse -o nonempty trellis-binaries /mnt/binaries']
          preStop:
            exec:
              command: ["fusermount", "-u", " /mnt/binaries"]
      restartPolicy: Always
      volumes:
      - name: datadir-trellis
        persistentVolumeClaim:
          claimName: datadir-trellis
