server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: h2
      port: 8445
      keyStorePath: /opt/trellis/etc/trellis.jks
      keyStorePassword: "changeme"
      validateCerts: false
      validatePeers: false
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/lib/trellis/log/access.log
        archive: true
        archivedLogFilenamePattern: /var/lib/trellis/log/access-%i.log
        archivedFileCount: 5
        maxFileSize: 100K

logging:
  level: WARN
  loggers:
    org.trellisldp: DEBUG
    io.dropwizard: DEBUG
  appenders:
    - type: console

binaries: /mnt/binaries

resources: http://fuseki:3030/fuseki/trellis

mementos: /var/lib/trellis/mementos

baseUrl: https://localhost:8445/

namespaces: /opt/trellis/etc/namespaces.json

auth:
    webac:
        enabled: true
    anon:
        enabled: true
    jwt:
        enabled: true
        base64Encoded: false
        key: secret
    basic:
        enabled: false
        usersFile: /opt/trellis/etc/users.auth

cors:
    enabled: true
    allowOrigin:
        - "*"
    maxAge: 180

notifications:
    max.request.size: 5000000
    enabled: true
    type: kafka
    topicName: "trellis"
    connectionString: "kafka:9094"

# JSON-LD configuration
jsonld:
    cacheSize: 10
    cacheExpireHours: 24
    contextWhitelist: []
    contextDomainWhitelist: []

