version: "3"

services:
  zoo1:
    image: zookeeper:3.5
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
       - "2181:2181"
       - "8500:8090"
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2182 server.3=zoo3:2888:3888;2183

  zoo2:
    image: zookeeper:3.5
    restart: always
    hostname: zoo2
    ports:
       - "2182:2181"
    environment:
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2182 server.3=zoo3:2888:3888;2183

  zoo3:
    image: zookeeper:3.5
    restart: always
    hostname: zoo3
    ports:
       - "2183:2181"
    environment:
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2182 server.3=zoo3:2888:3888;2183

  kafka:
    image: trellisldp/kafka:1.0.0
    ports:
        - "9094:9094"
        - "1099:1099"
    environment:
      HOSTNAME_COMMAND: "ifconfig|grep inet|head -1|sed 's/\\:/ /'|awk '{print $$3}'"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
     # KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
     # JMX_PORT: 1099
      KAFKA_MESSAGE_MAX_BYTES: 5000000
    volumes:
      - kafka-data-volume:/kafka

  trellis:
    image: trellisldp/trellis-app-8-ts:0.6.0
    container_name: trellis
    restart: always
    ports:
      - "8080:8080"
      - "8445:8445"
      - "8502:8081"
    volumes:
      - trellis-binary-volume:/mnt/binaries

  fuseki:
    image: trellisldp/fuseki
    container_name: fuseki
    restart: always
    environment:
        CATALINA_OPTS: -Xmx8G -Xss8M
    ports:
      - "3030:3030"
    volumes:
      - fuseki-volume:/shared

volumes:
  trellis-binary-volume:
    driver_opts:
      type: none
      device: /mnt/trellis-binaries
      o: bind
  kafka-data-volume:
    driver_opts:
      type: none
      device: /mnt/kafka-data
      o: bind
  fuseki-volume:
    driver_opts:
      type: none
      device: /mnt/fuseki-data
      o: bind